package io.kestra.plugin.huawei.koocli;

import io.kestra.core.models.annotations.Example;
import io.kestra.core.models.annotations.Plugin;
import io.kestra.core.models.annotations.PluginProperty;
import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.InputFilesInterface;
import io.kestra.core.models.tasks.NamespaceFiles;
import io.kestra.core.models.tasks.NamespaceFilesInterface;
import io.kestra.core.models.tasks.OutputFilesInterface;
import io.kestra.core.models.tasks.RunnableTask;
import io.kestra.core.models.tasks.runners.TaskRunner;
import io.kestra.core.runners.RunContext;
import io.kestra.plugin.huawei.AbstractConnection;
import io.kestra.plugin.scripts.exec.scripts.models.DockerOptions;
import io.kestra.plugin.scripts.exec.scripts.models.ScriptOutput;
import io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper;
import io.kestra.plugin.scripts.runner.docker.Docker;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
@Schema(
    title = "Execute KooCLI (hcloud) commands in a container.",
    description = """
        Runs one or more `hcloud` CLI commands inside the configured task runner (default: Docker with
        a glibc-based Ubuntu image). Automatically injects Huawei IAM credentials from `accessKeyId`
        / `secretAccessKey` (or an inline `temporaryCredentials` exchange) as environment variables
        and pre-configures `hcloud` with the region, output format, and security token.

        **KooCLI installation:** If `hcloud` is not present in the container image, it is downloaded
        automatically (~5 MB) from the official Huawei KooCLI distribution bucket on every run. For
        repeated executions, supply a prebuilt `containerImage` that already has `hcloud` installed —
        the install step is guarded by `command -v hcloud` and is skipped automatically.

        **Glibc requirement:** KooCLI is a dynamically linked glibc binary. Alpine/musl images are
        not supported. Use an Ubuntu/Debian-based image when supplying a custom `containerImage`.

        **Base tooling requirement:** If `curl` is not present in the image, the task first installs
        it via `apt-get` (guarded by `command -v curl`). The default `ubuntu:22.04` image does not
        ship with `curl`, so this step runs on first use and is skipped on subsequent runs or
        prebuilt images.

        Use `outputFiles` to persist files generated by CLI commands into Kestra internal storage.
        """
)
@Plugin(
    examples = {
        @Example(
            title = "Call an OBS API using the KooCLI and capture the output as a task output variable.",
            full = true,
            code = """
                id: koocli_list_obs_buckets
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    region: eu-west-101
                    commands:
                      - hcloud OBS ListBuckets | tr -d ' \\n' | xargs -0 -I {} echo '::{\"outputs\":{}}::'
                """
        ),
        @Example(
            title = "Run an hcloud command and write the output to a file, captured in Kestra internal storage.",
            full = true,
            code = """
                id: koocli_describe_vpc
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    region: eu-west-101
                    outputFiles:
                      - vpcs.json
                    commands:
                      - hcloud VPC ListVpcs --cli-region=eu-west-101 > vpcs.json
                """
        ),
        @Example(
            title = "Use a prebuilt container image with hcloud already installed to skip the per-run download.",
            full = true,
            code = """
                id: koocli_with_prebuilt_image
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    region: eu-west-101
                    containerImage: my-registry/hcloud-ready:latest
                    commands:
                      - hcloud version
                """
        )
    }
)
public class KooCLI extends AbstractConnection implements RunnableTask<ScriptOutput>, NamespaceFilesInterface, InputFilesInterface, OutputFilesInterface {

    // glibc-based image with curl, bash, and tar — required by the KooCLI install script.
    private static final String DEFAULT_IMAGE = "ubuntu:22.04";

    // Ensure curl + ca-certificates + tar are present before the KooCLI install script runs.
    // ubuntu:22.04 ships without curl; this step is guarded so prebuilt images with curl already
    // installed skip the apt-get entirely (no network call, no latency).
    private static final String APT_BOOTSTRAP_COMMAND =
        "command -v curl >/dev/null 2>&1 || " +
        "(apt-get update -qq && apt-get install -y --no-install-recommends curl ca-certificates tar)";

    // Official non-interactive KooCLI install script (downloads ~5 MB tarball, self-verifies SHA-256).
    private static final String INSTALL_COMMAND =
        "command -v hcloud >/dev/null 2>&1 || " +
        "(curl -sSL https://ap-southeast-3-hwcloudcli.obs.ap-southeast-3.myhuaweicloud.com/cli/latest/hcloud_install.sh " +
        "| bash -s -- -y)";

    // Auto-accept the first-run privacy prompt; without this, subsequent non-interactive commands block.
    private static final String CONSENT_COMMAND = "echo y | hcloud version >/dev/null 2>&1 || true";

    @Schema(
        title = "KooCLI (hcloud) commands to execute.",
        description = """
            Shell commands executed in order via `/bin/sh -c`. Each entry is a shell fragment; use
            pipes, redirects, and standard shell constructs as needed. The `hcloud` binary is
            available after the auto-install step that runs before your commands.
            """
    )
    @PluginProperty(group = "main")
    @NotNull
    protected Property<List<String>> commands;

    @Schema(
        title = "Additional environment variables.",
        description = """
            Extra variables merged into the process environment alongside the injected Huawei
            credentials (`HUAWEICLOUD_SDK_AK`, `HUAWEICLOUD_SDK_SK`). Values may contain Pebble
            expressions.
            """
    )
    @PluginProperty(group = "execution", additionalProperties = String.class, dynamic = true)
    protected Map<String, String> env;

    @Schema(
        title = "Deprecated Docker options.",
        description = "Use `taskRunner` instead; retained for backward compatibility."
    )
    @PluginProperty(group = "advanced")
    @Deprecated
    private DockerOptions docker;

    @Schema(
        title = "Task runner.",
        description = "Runner implementation for executing the CLI commands. Defaults to the Docker runner."
    )
    @PluginProperty(group = "execution")
    @Builder.Default
    @Valid
    private TaskRunner<?> taskRunner = Docker.instance();

    @Schema(
        title = "Container image.",
        description = """
            Docker image used when the runner is container-based. Defaults to `ubuntu:22.04`.

            **Bootstrap:** the task prepends two guarded steps before your commands:
            1. `command -v curl || apt-get install -y curl ca-certificates tar` — installs download
               tooling if absent (skipped on images that already have `curl`).
            2. `command -v hcloud || curl ... | bash -s -- -y` — downloads and installs KooCLI if
               absent (skipped on prebuilt images, eliminating the ~5 MB per-run fetch).

            **Prebuilt image:** pointing this at an image that already has `hcloud` installed
            causes both bootstrap steps to be skipped automatically. Useful for frequent
            executions where per-run install latency is unacceptable.

            **Glibc requirement:** KooCLI is a dynamically linked binary. Alpine/musl images
            cause a loader error at startup. Use an Ubuntu/Debian-based image.

            A minimal `Dockerfile` to build your own prebuilt image:
            ```dockerfile
            FROM ubuntu:22.04
            RUN apt-get update && apt-get install -y --no-install-recommends curl bash tar ca-certificates \\
                && curl -sSL https://ap-southeast-3-hwcloudcli.obs.ap-southeast-3.myhuaweicloud.com/cli/latest/hcloud_install.sh \\
                   | bash -s -- -y \\
                && echo y | hcloud version >/dev/null 2>&1 \\
                && rm -rf /var/lib/apt/lists/*
            ```
            """
    )
    @PluginProperty(dynamic = true, group = "execution")
    @Builder.Default
    private String containerImage = DEFAULT_IMAGE;

    @Schema(
        title = "KooCLI output format.",
        description = """
            Applied via `hcloud configure set --cli-output=<format>` before your commands run.
            Accepted values: `JSON`, `TABLE`, `TSV`. Defaults to `JSON`. Individual `hcloud`
            flags still take precedence over this setting.
            """
    )
    @PluginProperty(group = "processing")
    @Builder.Default
    protected OutputFormat outputFormat = OutputFormat.JSON;

    @PluginProperty(group = "source")
    private NamespaceFiles namespaceFiles;

    @PluginProperty(group = "source")
    private Object inputFiles;

    @PluginProperty(group = "destination")
    private Property<List<String>> outputFiles;

    @Override
    public ScriptOutput run(RunContext runContext) throws Exception {
        var clientConfig = huaweiClientConfig(runContext);

        var allCommands = new ArrayList<String>();
        allCommands.add(APT_BOOTSTRAP_COMMAND);
        allCommands.add(INSTALL_COMMAND);
        allCommands.add(CONSENT_COMMAND);

        // Pre-configure region and output format so user commands don't need to repeat --cli-region.
        if (clientConfig.region() != null) {
            allCommands.add("hcloud configure set --cli-region=" + clientConfig.region());
        }
        allCommands.add("hcloud configure set --cli-output=" + outputFormat.toString().toLowerCase());

        // Security token (for temporary credentials) must go through configure set; it cannot be
        // injected via env var alone in all KooCLI versions.
        if (clientConfig.securityToken() != null) {
            allCommands.add("hcloud configure set --cli-security-token=" + clientConfig.securityToken());
        }

        allCommands.addAll(runContext.render(this.commands).asList(String.class));

        var renderedOutputFiles = runContext.render(outputFiles).asList(String.class);

        var wrapper = new CommandsWrapper(runContext)
            .withWarningOnStdErr(true)
            .withDockerOptions(injectDefaults(getDocker()))
            .withTaskRunner(this.taskRunner)
            .withContainerImage(this.containerImage)
            .withInterpreter(Property.ofValue(List.of("/bin/sh", "-c")))
            .withCommands(Property.ofValue(allCommands))
            .withEnv(buildEnv(runContext, clientConfig))
            .withNamespaceFiles(namespaceFiles)
            .withInputFiles(inputFiles)
            .withOutputFiles(renderedOutputFiles.isEmpty() ? null : renderedOutputFiles);

        return wrapper.run();
    }

    private Map<String, String> buildEnv(
        RunContext runContext,
        AbstractConnection.HuaweiClientConfig clientConfig
    ) throws Exception {
        var envs = new HashMap<String, String>();

        // KooCLI reads credentials from these documented env vars.
        if (clientConfig.accessKeyId() != null) {
            envs.put("HUAWEICLOUD_SDK_AK", clientConfig.accessKeyId());
        }
        if (clientConfig.secretAccessKey() != null) {
            envs.put("HUAWEICLOUD_SDK_SK", clientConfig.secretAccessKey());
        }

        if (this.env != null) {
            // Render user-supplied env values (they may contain Pebble expressions).
            for (var entry : this.env.entrySet()) {
                envs.put(entry.getKey(), runContext.render(entry.getValue()));
            }
        }

        return envs;
    }

    private DockerOptions injectDefaults(DockerOptions original) {
        if (original == null) {
            return null;
        }

        var builder = original.toBuilder();
        if (original.getImage() == null) {
            builder.image(DEFAULT_IMAGE);
        }
        if (original.getEntryPoint() == null || original.getEntryPoint().isEmpty()) {
            builder.entryPoint(List.of(""));
        }

        return builder.build();
    }

    public enum OutputFormat {
        JSON,
        TABLE,
        TSV;

        @Override
        public String toString() {
            return super.toString().toLowerCase();
        }
    }
}
