package io.kestra.plugin.huawei.koocli;

import io.kestra.core.models.annotations.Example;
import io.kestra.core.models.annotations.Plugin;
import io.kestra.core.models.annotations.PluginProperty;
import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.InputFilesInterface;
import io.kestra.core.models.tasks.NamespaceFiles;
import io.kestra.core.models.tasks.NamespaceFilesInterface;
import io.kestra.core.models.tasks.OutputFilesInterface;
import io.kestra.core.models.tasks.RunnableTask;
import io.kestra.core.models.tasks.runners.TaskRunner;
import io.kestra.core.runners.RunContext;
import io.kestra.plugin.huawei.AbstractConnection;
import io.kestra.plugin.scripts.exec.scripts.models.DockerOptions;
import io.kestra.plugin.scripts.exec.scripts.models.ScriptOutput;
import io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper;
import io.kestra.plugin.scripts.runner.docker.Docker;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
@Schema(
    title = "Execute KooCLI (hcloud) commands in a container.",
    description = """
        Runs one or more `hcloud` CLI commands inside the configured task runner (default: Docker with
        a glibc-based Ubuntu image). Automatically injects Huawei IAM credentials and region via
        environment variables (`HUAWEICLOUD_SDK_AK`, `HUAWEICLOUD_SDK_SK`, `HUAWEICLOUD_SDK_REGION`,
        and `HUAWEICLOUD_SDK_SECURITY_TOKEN` for temporary credentials).

        **Credential injection:** AK/SK, region, and security token are set as env vars — not as
        argv secrets — so they are never visible in process listings.

        **Output format:** KooCLI does not support a global output format setting. Pass
        `--cli-output=json` (or `table`, `tsv`) per command when needed.

        **KooCLI installation:** If `hcloud` is not present in the container image, two guarded
        bootstrap steps run first:
        1. `command -v curl || apt-get install -y curl ca-certificates tar` — the default
           `ubuntu:22.04` image ships without `curl`; this installs it when absent.
        2. `command -v hcloud || curl ... | bash -s -- -y` — downloads the KooCLI binary (~5 MB)
           from the official Huawei distribution bucket.
        Both steps are skipped automatically on prebuilt images that already have `curl` and `hcloud`.

        **Glibc requirement:** KooCLI is a dynamically linked glibc binary. Alpine/musl images are
        not supported.

        Use `outputFiles` to persist files generated by CLI commands into Kestra internal storage.
        """
)
@Plugin(
    examples = {
        @Example(
            title = "List OBS buckets and capture the JSON output as a task output variable.",
            full = true,
            code = """
                id: koocli_list_obs_buckets
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    region: eu-west-101
                    commands:
                      - hcloud OBS ListBuckets --cli-output=json | tr -d ' \\n' | xargs -0 -I {} echo '::{\"outputs\":{}}::'
                """
        ),
        @Example(
            title = "Write VPC list to a file captured in Kestra internal storage.",
            full = true,
            code = """
                id: koocli_list_vpcs
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    region: eu-west-101
                    outputFiles:
                      - vpcs.json
                    commands:
                      - hcloud VPC ListVpcs --cli-output=json > vpcs.json
                """
        ),
        @Example(
            title = "Use a prebuilt container image with hcloud already installed to skip the per-run download.",
            full = true,
            code = """
                id: koocli_with_prebuilt_image
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    region: eu-west-101
                    containerImage: my-registry/hcloud-ready:latest
                    commands:
                      - hcloud version
                """
        )
    }
)
public class KooCLI extends AbstractConnection implements RunnableTask<ScriptOutput>, NamespaceFilesInterface, InputFilesInterface, OutputFilesInterface {

    // glibc-based image; does NOT ship with curl — the APT_BOOTSTRAP_COMMAND handles that.
    private static final String DEFAULT_IMAGE = "ubuntu:22.04";

    // ubuntu:22.04 ships without curl; install it (plus ca-certificates for HTTPS and tar for the
    // KooCLI tarball) only when absent. Guarded so prebuilt images with curl skip the apt-get.
    private static final String APT_BOOTSTRAP_COMMAND =
        "command -v curl >/dev/null 2>&1 || " +
        "(apt-get update -qq && apt-get install -y --no-install-recommends curl ca-certificates tar)";

    // Official non-interactive KooCLI install script (downloads ~5 MB tarball, self-verifies SHA-256).
    // Guarded so prebuilt images with hcloud already present skip the download entirely.
    private static final String INSTALL_COMMAND =
        "command -v hcloud >/dev/null 2>&1 || " +
        "(curl -sSL https://ap-southeast-3-hwcloudcli.obs.ap-southeast-3.myhuaweicloud.com/cli/latest/hcloud_install.sh " +
        "| bash -s -- -y)";

    // Auto-accept the first-run privacy prompt; without this, subsequent non-interactive commands block.
    private static final String CONSENT_COMMAND = "echo y | hcloud version >/dev/null 2>&1 || true";

    @Schema(
        title = "KooCLI (hcloud) commands to execute.",
        description = """
            Shell commands executed in order via `/bin/sh -c`. Each entry is a shell fragment; use
            pipes, redirects, and standard shell constructs as needed. The `hcloud` binary is
            available after the auto-install step that runs before your commands.

            **Output format:** KooCLI has no global output format setting. Pass `--cli-output=json`
            (or `table`, `tsv`) per command: `hcloud SVC Op --cli-output=json`.
            """
    )
    @PluginProperty(group = "main")
    @NotNull
    protected Property<List<String>> commands;

    @Schema(
        title = "Additional environment variables.",
        description = """
            Extra variables merged into the process environment alongside the injected Huawei
            credentials (`HUAWEICLOUD_SDK_AK`, `HUAWEICLOUD_SDK_SK`, `HUAWEICLOUD_SDK_REGION`,
            `HUAWEICLOUD_SDK_SECURITY_TOKEN`). Values may contain Pebble expressions.
            """
    )
    @PluginProperty(group = "execution", additionalProperties = String.class, dynamic = true)
    protected Map<String, String> env;

    @Schema(
        title = "Deprecated Docker options.",
        description = "Use `taskRunner` instead; retained for backward compatibility."
    )
    @PluginProperty(group = "advanced")
    @Deprecated
    private DockerOptions docker;

    @Schema(
        title = "Task runner.",
        description = "Runner implementation for executing the CLI commands. Defaults to the Docker runner."
    )
    @PluginProperty(group = "execution")
    @Builder.Default
    @Valid
    private TaskRunner<?> taskRunner = Docker.instance();

    @Schema(
        title = "Container image.",
        description = """
            Docker image used when the runner is container-based. Defaults to `ubuntu:22.04`.

            **Bootstrap:** the task prepends two guarded steps before your commands:
            1. `command -v curl || apt-get install -y curl ca-certificates tar` — installs download
               tooling if absent (skipped on images that already have `curl`).
            2. `command -v hcloud || curl ... | bash -s -- -y` — downloads and installs KooCLI if
               absent (skipped on prebuilt images, eliminating the ~5 MB per-run fetch).

            **Prebuilt image:** pointing this at an image that already has `hcloud` installed
            causes both bootstrap steps to be skipped automatically. Useful for frequent
            executions where per-run install latency is unacceptable.

            **Glibc requirement:** KooCLI is a dynamically linked binary. Alpine/musl images
            cause a loader error at startup. Use an Ubuntu/Debian-based image.

            A minimal `Dockerfile` to build your own prebuilt image:
            ```dockerfile
            FROM ubuntu:22.04
            RUN apt-get update && apt-get install -y --no-install-recommends curl bash tar ca-certificates \\
                && curl -sSL https://ap-southeast-3-hwcloudcli.obs.ap-southeast-3.myhuaweicloud.com/cli/latest/hcloud_install.sh \\
                   | bash -s -- -y \\
                && echo y | hcloud version >/dev/null 2>&1 \\
                && rm -rf /var/lib/apt/lists/*
            ```
            """
    )
    @PluginProperty(dynamic = true, group = "execution")
    @Builder.Default
    private String containerImage = DEFAULT_IMAGE;

    @PluginProperty(group = "source")
    private NamespaceFiles namespaceFiles;

    @PluginProperty(group = "source")
    private Object inputFiles;

    @PluginProperty(group = "destination")
    private Property<List<String>> outputFiles;

    @Override
    public ScriptOutput run(RunContext runContext) throws Exception {
        var clientConfig = huaweiClientConfig(runContext);

        var allCommands = new ArrayList<String>();
        allCommands.add(APT_BOOTSTRAP_COMMAND);
        allCommands.add(INSTALL_COMMAND);
        allCommands.add(CONSENT_COMMAND);
        allCommands.addAll(runContext.render(this.commands).asList(String.class));

        var renderedOutputFiles = runContext.render(outputFiles).asList(String.class);

        var wrapper = new CommandsWrapper(runContext)
            .withWarningOnStdErr(true)
            .withDockerOptions(injectDefaults(getDocker()))
            .withTaskRunner(this.taskRunner)
            .withContainerImage(this.containerImage)
            .withInterpreter(Property.ofValue(List.of("/bin/sh", "-c")))
            .withCommands(Property.ofValue(allCommands))
            .withEnv(buildEnv(runContext, clientConfig))
            .withNamespaceFiles(namespaceFiles)
            .withInputFiles(inputFiles)
            .withOutputFiles(renderedOutputFiles.isEmpty() ? null : renderedOutputFiles);

        return wrapper.run();
    }

    private Map<String, String> buildEnv(
        RunContext runContext,
        AbstractConnection.HuaweiClientConfig clientConfig
    ) throws Exception {
        var envs = new HashMap<String, String>();

        // KooCLI reads credentials and region from these documented env vars.
        if (clientConfig.accessKeyId() != null) {
            envs.put("HUAWEICLOUD_SDK_AK", clientConfig.accessKeyId());
        }
        if (clientConfig.secretAccessKey() != null) {
            envs.put("HUAWEICLOUD_SDK_SK", clientConfig.secretAccessKey());
        }
        // Region injected via env var — hcloud configure set --cli-region requires a full profile
        // (AK/SK on argv) which would expose secrets; env var achieves the same cleanly.
        if (clientConfig.region() != null) {
            envs.put("HUAWEICLOUD_SDK_REGION", clientConfig.region());
        }
        // Security token for temporary credentials, injected via env var for the same reason.
        if (clientConfig.securityToken() != null) {
            envs.put("HUAWEICLOUD_SDK_SECURITY_TOKEN", clientConfig.securityToken());
        }

        if (this.env != null) {
            // Render user-supplied env values (they may contain Pebble expressions).
            for (var entry : this.env.entrySet()) {
                envs.put(entry.getKey(), runContext.render(entry.getValue()));
            }
        }

        return envs;
    }

    private DockerOptions injectDefaults(DockerOptions original) {
        if (original == null) {
            return null;
        }

        var builder = original.toBuilder();
        if (original.getImage() == null) {
            builder.image(DEFAULT_IMAGE);
        }
        if (original.getEntryPoint() == null || original.getEntryPoint().isEmpty()) {
            builder.entryPoint(List.of(""));
        }

        return builder.build();
    }
}
