package io.kestra.plugin.huawei.koocli;

import io.kestra.core.models.annotations.Example;
import io.kestra.core.models.annotations.Plugin;
import io.kestra.core.models.annotations.PluginProperty;
import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.InputFilesInterface;
import io.kestra.core.models.tasks.NamespaceFiles;
import io.kestra.core.models.tasks.NamespaceFilesInterface;
import io.kestra.core.models.tasks.OutputFilesInterface;
import io.kestra.core.models.tasks.RunnableTask;
import io.kestra.core.models.tasks.runners.TaskRunner;
import io.kestra.core.runners.RunContext;
import io.kestra.plugin.huawei.AbstractConnection;
import io.kestra.plugin.scripts.exec.scripts.models.DockerOptions;
import io.kestra.plugin.scripts.exec.scripts.models.ScriptOutput;
import io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper;
import io.kestra.plugin.scripts.runner.docker.Docker;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
@Schema(
    title = "Execute KooCLI (hcloud) commands in a container.",
    description = """
        Runs one or more `hcloud` CLI commands inside the configured task runner (default: Docker with
        a glibc-based Ubuntu image). The task automatically configures a KooCLI profile from this
        plugin's connection properties (access key, secret key, region, and security token), so
        commands run authenticated against the configured `region` without passing `--cli-region`
        or credentials manually. Secret values are never exposed on the command line or in logs.

        **Output format:** KooCLI has no global output setting. Pass `--cli-output=json` (or `table`,
        `tsv`) per command when needed.

        **Installation:** if `hcloud` is not already in the container image, it is downloaded and
        installed automatically on first run (skipped on prebuilt images).

        **Cloud partition:** the correct `hcloud` binary is selected automatically. Standard regions
        and the EU Sovereign Cloud region `eu-west-101` both work with no extra configuration. Set
        `installScriptUrl` only for a private/dedicated (HCS) cloud or a partition not yet known to
        this plugin.

        **Glibc requirement:** KooCLI is a dynamically linked glibc binary; Alpine/musl images are
        not supported.

        Use `outputFiles` to persist files generated by CLI commands into Kestra internal storage.
        """
)
@Plugin(
    examples = {
        @Example(
            title = "List IAM projects and capture the JSON output as a task output variable.",
            full = true,
            code = """
                id: koocli_list_projects
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    region: eu-west-101
                    commands:
                      - hcloud IAM KeystoneListProjects --cli-output=json | tr -d ' \\n' | xargs -0 -I {} echo '::{\"outputs\":{}}::'
                """
        ),
        @Example(
            title = "Write VPC list to a file captured in Kestra internal storage.",
            full = true,
            code = """
                id: koocli_list_vpcs
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    region: eu-west-101
                    outputFiles:
                      - vpcs.json
                    commands:
                      - hcloud VPC ListVpcs --cli-output=json > vpcs.json
                """
        ),
        @Example(
            title = "Use a prebuilt container image with hcloud already installed to skip the per-run download.",
            full = true,
            code = """
                id: koocli_with_prebuilt_image
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    region: eu-west-101
                    containerImage: my-registry/hcloud-ready:latest
                    commands:
                      - hcloud version
                """
        ),
        @Example(
            title = "EU Sovereign Cloud: the region-specific KooCLI binary is selected automatically, no installScriptUrl needed.",
            full = true,
            code = """
                id: koocli_eu_sovereign_cloud
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    region: eu-west-101
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    commands:
                      - hcloud IAM KeystoneListProjects --cli-output=json
                """
        ),
        @Example(
            title = "Private/dedicated (HCS) cloud: override installScriptUrl with your deployment's own install script.",
            full = true,
            code = """
                id: koocli_hcs_private_cloud
                namespace: company.team
                tasks:
                  - id: cli
                    type: io.kestra.plugin.huawei.koocli.KooCLI
                    region: hcs-region-1
                    installScriptUrl: https://hcloudcli.my-hcs-domain.example.com/cli/latest/hcloud_install.sh
                    accessKeyId: "{{ secret('HUAWEI_ACCESS_KEY_ID') }}"
                    secretAccessKey: "{{ secret('HUAWEI_SECRET_ACCESS_KEY') }}"
                    commands:
                      - hcloud IAM KeystoneListProjects --cli-output=json
                """
        )
    }
)
public class KooCLI extends AbstractConnection implements RunnableTask<ScriptOutput>, NamespaceFilesInterface, InputFilesInterface, OutputFilesInterface {

    // glibc-based image; does NOT ship with curl. The APT_BOOTSTRAP_COMMAND handles that.
    private static final String DEFAULT_IMAGE = "ubuntu:22.04";

    // ubuntu:22.04 ships without curl; install it (plus ca-certificates for HTTPS and tar for the
    // KooCLI tarball) only when absent. Guarded so prebuilt images with curl skip the apt-get.
    // Output (stdout+stderr) is captured and only echoed (at ERROR) if the install fails, so a
    // successful bootstrap stays silent instead of flooding the logs with apt/debconf chatter.
    // DEBIAN_FRONTEND=noninteractive avoids the interactive debconf path.
    private static final String APT_BOOTSTRAP_COMMAND =
        "command -v curl >/dev/null 2>&1 || " +
        "__koocli_out=$({ DEBIAN_FRONTEND=noninteractive apt-get update -qq && " +
        "DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends curl ca-certificates tar; } 2>&1) || " +
        "{ echo \"$__koocli_out\" >&2; exit 1; }";

    // International cloud partition (myhuaweicloud.com) install script. This binary covers the full
    // standard region catalog (cn-*/ap-*/la-*/na-*/af-*/me-*/ru-*/tr-*/ae-*/sa-*, plus eu-west-0), so
    // it's the correct fallback for every region NOT listed in SOVEREIGN_INSTALL_URLS below.
    private static final String INTERNATIONAL_INSTALL_URL =
        "https://ap-southeast-3-hwcloudcli.obs.ap-southeast-3.myhuaweicloud.com/cli/latest/hcloud_install.sh";

    // Sovereign/regional partitions ship their own KooCLI binary with their own baked-in region
    // catalog; the international binary rejects these regions outright. Add new sovereign regions
    // here as Huawei publishes them. Anything not listed here falls back to the international
    // binary above; installScriptUrl remains the escape hatch for private/dedicated (HCS) clouds
    // or any future partition not yet known to this plugin.
    private static final Map<String, String> SOVEREIGN_INSTALL_URLS = Map.of(
        "eu-west-101", "https://eu-west-101-apiexplorer-cli.obs.eu-west-101.myhuaweicloud.eu/cli/latest/hcloud_install.sh"
    );

    // Auto-accept the first-run privacy prompt; without this, subsequent non-interactive commands block.
    private static final String CONSENT_COMMAND = "echo y | hcloud version >/dev/null 2>&1 || true";

    @Schema(
        title = "KooCLI (hcloud) commands to execute.",
        description = """
            Shell commands executed in order via `/bin/sh -c`. Each entry is a shell fragment; use
            pipes, redirects, and standard shell constructs as needed. The `hcloud` binary is
            available after the auto-install step that runs before your commands.

            **Output format:** KooCLI has no global output format setting. Pass `--cli-output=json`
            (or `table`, `tsv`) per command: `hcloud SVC Op --cli-output=json`.
            """
    )
    @PluginProperty(group = "main")
    @NotNull
    protected Property<List<String>> commands;

    @Schema(
        title = "KooCLI install script URL override.",
        description = """
            URL of the non-interactive KooCLI (`hcloud`) install script, used only when `hcloud` is
            not already present in the container image. Optional; leave unset for standard and EU
            Sovereign Cloud regions, both resolved automatically.

            Each KooCLI binary is built for exactly one cloud partition and ships with that
            partition's region catalog baked in; it validates `--cli-region` against this catalog
            and there is no way to override it at runtime (not even via `--cli-endpoint`). This
            plugin resolves the correct binary automatically in most cases:

            1. If this property is set, it always wins (escape hatch for private/dedicated clouds,
               a.k.a. HCS, or any future partition not yet known to this plugin).
            2. Otherwise, if `region` is a known sovereign region (currently `eu-west-101`), the
               matching EU Sovereign Cloud binary is selected automatically.
            3. Otherwise, the international binary is used; it covers the full standard region
               catalog (`cn-*`, `ap-*`, `la-*`, `na-*`, `af-*`, `me-*`, `ru-*`, `tr-*`, `ae-*`,
               `sa-*`, and `eu-west-0`).

            Set this only when your region belongs to a partition not covered by tiers 2 or 3 above,
            e.g. a private/dedicated (HCS) deployment.

            Ignored entirely when `hcloud` is already installed in the container image (the install
            step is guarded and skips itself).
            """
    )
    @PluginProperty(group = "execution", dynamic = true)
    protected Property<String> installScriptUrl;

    @Schema(
        title = "Additional environment variables.",
        description = """
            Extra variables merged into the process environment alongside the injected Huawei
            credentials (`HUAWEICLOUD_SDK_AK`, `HUAWEICLOUD_SDK_SK`, `HUAWEICLOUD_SDK_REGION`,
            `HUAWEICLOUD_SDK_SECURITY_TOKEN`). Values may contain Pebble expressions.
            """
    )
    @PluginProperty(group = "execution", additionalProperties = String.class, dynamic = true)
    protected Map<String, String> env;

    @Schema(
        title = "Deprecated Docker options.",
        description = "Use `taskRunner` instead; retained for backward compatibility."
    )
    @PluginProperty(group = "advanced")
    @Deprecated
    private DockerOptions docker;

    @Schema(
        title = "Task runner.",
        description = "Runner implementation for executing the CLI commands. Defaults to the Docker runner."
    )
    @PluginProperty(group = "execution")
    @Builder.Default
    @Valid
    private TaskRunner<?> taskRunner = Docker.instance();

    @Schema(
        title = "Container image.",
        description = """
            Docker image used when the runner is container-based. Defaults to `ubuntu:22.04`.

            **Bootstrap:** the task prepends two guarded steps before your commands:
            1. `command -v curl || apt-get install -y curl ca-certificates tar`: installs download
               tooling if absent (skipped on images that already have `curl`).
            2. `command -v hcloud || curl ... | bash -s -- -y`: downloads and installs KooCLI if
               absent (skipped on prebuilt images, eliminating the ~5 MB per-run fetch).

            **Prebuilt image:** pointing this at an image that already has `hcloud` installed
            causes both bootstrap steps to be skipped automatically. Useful for frequent
            executions where per-run install latency is unacceptable.

            **Glibc requirement:** KooCLI is a dynamically linked binary. Alpine/musl images
            cause a loader error at startup. Use an Ubuntu/Debian-based image.

            A minimal `Dockerfile` to build your own prebuilt image:
            ```dockerfile
            FROM ubuntu:22.04
            RUN apt-get update && apt-get install -y --no-install-recommends curl bash tar ca-certificates \\
                && curl -sSL https://ap-southeast-3-hwcloudcli.obs.ap-southeast-3.myhuaweicloud.com/cli/latest/hcloud_install.sh \\
                   | bash -s -- -y \\
                && echo y | hcloud version >/dev/null 2>&1 \\
                && rm -rf /var/lib/apt/lists/*
            ```
            """
    )
    @PluginProperty(dynamic = true, group = "execution")
    @Builder.Default
    private String containerImage = DEFAULT_IMAGE;

    @PluginProperty(group = "source")
    private NamespaceFiles namespaceFiles;

    @PluginProperty(group = "source")
    private Object inputFiles;

    @PluginProperty(group = "destination")
    private Property<List<String>> outputFiles;

    @Override
    public ScriptOutput run(RunContext runContext) throws Exception {
        var clientConfig = huaweiClientConfig(runContext);
        var rInstallScriptUrl = runContext.render(this.installScriptUrl).as(String.class).orElse(null);
        var resolvedInstallScriptUrl = resolveInstallScriptUrl(rInstallScriptUrl, clientConfig.region());

        var allCommands = new ArrayList<String>();
        allCommands.add(APT_BOOTSTRAP_COMMAND);
        allCommands.add(buildInstallCommand(resolvedInstallScriptUrl));
        allCommands.add(CONSENT_COMMAND);
        var configureCommand = buildConfigureCommand(clientConfig);
        if (configureCommand != null) {
            allCommands.add(configureCommand);
        }
        allCommands.addAll(runContext.render(this.commands).asList(String.class));

        var renderedOutputFiles = runContext.render(outputFiles).asList(String.class);

        var wrapper = new CommandsWrapper(runContext)
            .withWarningOnStdErr(true)
            .withDockerOptions(injectDefaults(getDocker()))
            .withTaskRunner(this.taskRunner)
            .withContainerImage(this.containerImage)
            .withInterpreter(Property.ofValue(List.of("/bin/sh", "-c")))
            .withCommands(Property.ofValue(allCommands))
            .withEnv(buildEnv(runContext, clientConfig))
            .withNamespaceFiles(namespaceFiles)
            .withInputFiles(inputFiles)
            .withOutputFiles(renderedOutputFiles.isEmpty() ? null : renderedOutputFiles);

        return wrapper.run();
    }

    private Map<String, String> buildEnv(
        RunContext runContext,
        AbstractConnection.HuaweiClientConfig clientConfig
    ) throws Exception {
        var envs = new HashMap<String, String>();

        // Not read directly by hcloud; these are consumed by buildConfigureCommand() to write a
        // profile, and kept in the environment so process listings never show the secret values.
        if (clientConfig.accessKeyId() != null) {
            envs.put("HUAWEICLOUD_SDK_AK", clientConfig.accessKeyId());
        }
        if (clientConfig.secretAccessKey() != null) {
            envs.put("HUAWEICLOUD_SDK_SK", clientConfig.secretAccessKey());
        }
        if (clientConfig.region() != null) {
            envs.put("HUAWEICLOUD_SDK_REGION", clientConfig.region());
        }
        if (clientConfig.securityToken() != null) {
            envs.put("HUAWEICLOUD_SDK_SECURITY_TOKEN", clientConfig.securityToken());
        }

        if (this.env != null) {
            // Render user-supplied env values (they may contain Pebble expressions).
            for (var entry : this.env.entrySet()) {
                envs.put(entry.getKey(), runContext.render(entry.getValue()));
            }
        }

        return envs;
    }

    // Tier 1: explicit override always wins (HCS/dedicated clouds, future partitions).
    // Tier 2: known sovereign region auto-selects its own binary.
    // Tier 3: everything else falls back to the international binary (full standard catalog).
    private static String resolveInstallScriptUrl(String renderedOverride, String region) {
        if (renderedOverride != null && !renderedOverride.isBlank()) {
            return renderedOverride;
        }
        if (region != null && SOVEREIGN_INSTALL_URLS.containsKey(region)) {
            return SOVEREIGN_INSTALL_URLS.get(region);
        }
        return INTERNATIONAL_INSTALL_URL;
    }

    // Official non-interactive KooCLI install script (downloads ~5 MB tarball, self-verifies SHA-256).
    // Guarded so prebuilt images with hcloud already present skip the download entirely.
    // Same pattern as the apt step: the script's internal curl prints a progress meter, so capture
    // stdout+stderr and only surface it (at ERROR) if the install actually fails.
    private static String buildInstallCommand(String url) {
        return "command -v hcloud >/dev/null 2>&1 || " +
            "__koocli_out=$({ curl -sSL " + url + " | bash -s -- -y; } 2>&1) || " +
            "{ echo \"$__koocli_out\" >&2; exit 1; }";
    }

    // KooCLI does not read region (or credentials) from environment variables; it requires
    // --cli-region/--cli-access-key or a profile. Write a `default` profile via `configure set`,
    // referencing the injected env vars BY SHELL NAME ("$HUAWEICLOUD_SDK_AK", ...) so the actual
    // secret values never appear on argv or in Kestra logs. The shell expands them at runtime
    // inside the isolated container. This makes the `region` property take effect for every command.
    private String buildConfigureCommand(AbstractConnection.HuaweiClientConfig clientConfig) {
        var parts = new ArrayList<String>();
        parts.add("hcloud configure set --cli-profile=default");
        if (clientConfig.accessKeyId() != null) {
            parts.add("--cli-access-key=\"$HUAWEICLOUD_SDK_AK\"");
        }
        if (clientConfig.secretAccessKey() != null) {
            parts.add("--cli-secret-key=\"$HUAWEICLOUD_SDK_SK\"");
        }
        if (clientConfig.securityToken() != null) {
            parts.add("--cli-security-token=\"$HUAWEICLOUD_SDK_SECURITY_TOKEN\"");
        }
        if (clientConfig.region() != null) {
            parts.add("--cli-region=\"$HUAWEICLOUD_SDK_REGION\"");
        }
        return parts.size() == 1 ? null : String.join(" ", parts);
    }

    private DockerOptions injectDefaults(DockerOptions original) {
        if (original == null) {
            return null;
        }

        var builder = original.toBuilder();
        if (original.getImage() == null) {
            builder.image(DEFAULT_IMAGE);
        }
        if (original.getEntryPoint() == null || original.getEntryPoint().isEmpty()) {
            builder.entryPoint(List.of(""));
        }

        return builder.build();
    }
}
